### ISSUE TITLE
在线demo无法识别手势以及添加手势

### ISSUE THREAD

**Issue by itbeihe** [ElemeFE/smart-gesture#17]
添加手势浏览器报错

Uncaught TypeError: Cannot read property 'x' of undefined

#### smart-gesture version
1.2.1 

#### OS/Browers version
win/Chrome 52

**Comment by YongX** [comment]
是说这个 https://elemefe.github.io/smart-gesture/ 地址里面的demo？ 
我刚刚试了下是OK的呢

**Comment by YongX** [comment]
啊，知道了。自定义手势的添加是要先画图形，然后再设置对应的手势名的。现在不支持直接上来先设置手势名的方式。

**Comment by itbeihe** [comment]
没问题了,辛苦。
