### ISSUE TITLE
容器的外层元素有上 margin 或者上 padding 时，绘制路径计算有偏差；

### ISSUE THREAD

**Issue by ioslh** [ElemeFE/smart-gesture#24]
### smart-gesture version
1.2.2

### OS/Browers version
macOS/Chrome 54.0.2840.71 (Official Build) (64-bit)

### Reproduction Link

https://jsfiddle.net/ioslh/j9nvyjce/2/

### What is actually happening?
容器的外层元素（不仅仅是父级元素）有上 margin 或者上 padding 时，绘制路径计算有偏差；

**Comment by YongX** [comment]
fixed in version 1.2.3.
