### ISSUE TITLE
清理devDependencies里的引入

### ISSUE THREAD

**Issue by jabbany** [ElemeFE/smart-gesture#28]
先行抱歉没有采用 Issues 模板，这个ticket情况比较特殊。

最近GitHub加入了可以查看node模块互相导入的功能，我发现 `comment-core-library` 在这个库的`devDependencies`列表里面，然而并没有搞明白用到了什么（感觉并没有被用到= =）。

是不是应该考虑清理一下这个项目的引入。。。？

**Comment by YongX** [comment]
hi 感谢提 issue，这个项目倒是很久没管了。没想到还有人使用~

后面我会重新整理下这个项目，实际上这里面还稍微有一个隐藏的小 BUG 一直比较懒没去管，这样的话也顺便一起来看解决了。

保持关注吧。

**Comment by YongX** [comment]
已清理。
